export const CREATE_CLASS_REQUEST = "CREATE_CLASS_REQUEST";
export const CREATE_CLASS_SUCCESS = "CREATE_CLASS_SUCCESS";
export const CREATE_CLASS_FAIL = "CREATE_CLASS_FAIL";
export const CREATE_CLASS_RESET = "CREATE_CLASS_RESET";

export const DELETE_CLASS_REQUEST = "DELETE_CLASS_REQUEST";
export const DELETE_CLASS_SUCCESS = "DELETE_CLASS_SUCCESS";
export const DELETE_CLASS_FAIL = "DELETE_CLASS_FAIL";
export const DELETE_CLASS_RESET = "DELETE_CLASS_RESET";

export const GET_CLASSES_REQUEST = "GET_CLASSES_REQUEST";
export const GET_CLASSES_SUCCESS = "GET_CLASSES_SUCCESS";
export const GET_CLASSES_FAIL = "GET_CLASSES_FAIL";
export const GET_CLASSES_RESET = "GET_CLASSES_RESET";

export const EDIT_CLASS_REQUEST = "EDIT_CLASS_REQUEST";
export const EDIT_CLASS_SUCCESS = "EDIT_CLASS_SUCCESS";
export const EDIT_CLASS_FAIL = "EDIT_CLASS_FAIL";
export const EDIT_CLASS_RESET = "EDIT_CLASS_RESET";

export const JOIN_CLASS_BYCODE_REQUEST = "JOIN_CLASS_BYCODE_REQUEST";
export const JOIN_CLASS_BYCODE_SUCCESS = "JOIN_CLASS_BYCODE_SUCCESS";
export const JOIN_CLASS_BYCODE_FAIL = "JOIN_CLASS_BYCODE_FAIL";
export const JOIN_CLASS_BYCODE_RESET = "JOIN_CLASS_BYCODE_RESET";

export const UNSUB_CLASS_REQUEST = "UNSUB_CLASS_REQUEST";
export const UNSUB_CLASS_SUCCESS = "UNSUB_CLASS_SUCCESS";
export const UNSUB_CLASS_FAIL = "UNSUB_CLASS_FAIL";
export const UNSUB_CLASS_RESET = "UNSUB_CLASS_RESET";

export const EDIT_ASM_REQUEST = "EDIT_ASM_REQUEST";
export const EDIT_ASM_SUCCESS = "EDIT_ASM_SUCCESS";
export const EDIT_ASM_FAIL = "EDIT_ASM_FAIL";
export const EDIT_ASM_RESET = "EDIT_ASM_RESET";
