export const CREATE_CLASS_REQUEST = "CREATE_CLASS_REQUEST";
export const CREATE_CLASS_SUCCESS = "CREATE_CLASS_SUCCESS";
export const CREATE_CLASS_FAIL = "CREATE_CLASS_FAIL";
export const CREATE_CLASS_RESET = "CREATE_CLASS_RESET";

export const GET_CLASSES_REQUEST = "GET_CLASSES_REQUEST";
export const GET_CLASSES_SUCCESS = "GET_CLASSES_SUCCESS";
export const GET_CLASSES_FAIL = "GET_CLASSES_FAIL";
export const GET_CLASSES_RESET = "GET_CLASSES_RESET";

export const EDIT_CLASS_REQUEST = "EDIT_CLASS_REQUEST";
export const EDIT_CLASS_SUCCESS = "EDIT_CLASS_SUCCESS";
export const EDIT_CLASS_FAIL = "EDIT_CLASS_FAIL";
export const EDIT_CLASS_RESET = "EDIT_CLASS_RESET";
